### PR TITLE
updates for 0.12

### PR DESCRIPTION
**Pull request by Thimoteus**
surprisingly simple

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! I've added you as collaborator, so please feel free to merge and make a release.

I think Travis can be appeased by copying the config from one of my other repos.

**Comment by justinwoo** [comment]
e.g. https://github.com/purescript-contrib/purescript-string-parsers/blob/master/.travis.yml

**Comment by justinwoo** [comment]
Need to remove purescript from package.json: https://github.com/paf31/purescript-safely/blob/ef7377d7f7659250f2f4a5da02c5d229e4eeed53/package.json#L10

**Comment by Thimoteus** [comment]
Thanks @paf31 @justinwoo

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
